# Site settings
title: Welcome to Vince Velocci's Data Science Blog!
email: velocci@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  A selection of my data projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.io" # the base hostname & protocol for your site
twitter_username: @vince_velocci
github_username:  unif2

# Build settings
markdown: kramdown

paginate: 4

author: Vince Velocci

gems: [jekyll-paginate]
